import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import QRCode from "qrcode";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { Button } from "@/components/ui/button";
import { formatKg } from "@/lib/utils";
export default async function Waybill({params}:{params:Promise<{id:string}>}){const s=await auth();if(!s?.user)redirect("/login");const {id}=await params;const t=await prisma.weighbridgeTransaction.findUnique({where:{id},include:{site:{include:{organisation:true}},vehicle:true,trailer:true,driver:true,operator:true,booking:{include:{transporterOrganisation:true,order:{include:{originSite:true,destinationSite:true}},additionalTrailers:{include:{trailer:true},orderBy:{position:"asc"}}}}}});if(!t)notFound();const url=`${process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000"}/verify/${t.integrityHash}`;const qr=await QRCode.toDataURL(url,{width:220,margin:1});const tz=t.site.timezone;const order=t.booking.order;const isDispatch=order?.type==="DISPATCH";const supplierOrigin=isDispatch?t.site.name:(order?.supplierName??order?.originSite?.name??"—");const destination=isDispatch?(order?.customerName??order?.destinationSite?.name??"—"):t.site.name;const trailerRegs=[t.trailer?(t.trailer.registrationNo??t.trailer.trailerId):null,...t.booking.additionalTrailers.map(bt=>bt.trailer.registrationNo??bt.trailer.trailerId)].filter((v):v is string=>Boolean(v));const trailerReg=trailerRegs.length?trailerRegs.join(" "):null;const reprintFlag=t.printCount>0?"&reprint=true":"";return <main className="min-h-screen bg-slate-100 p-4 print:bg-white print:text-black"><div className="mx-auto max-w-3xl rounded-lg bg-white p-8 text-zinc-950 shadow-2xl print:shadow-none"><div className="flex items-start justify-between border-b-2 border-zinc-900 pb-4"><div><h1 className="text-xl font-bold">{t.site.name}</h1><p className="text-xs text-zinc-600">{t.site.address}</p><p className="text-xs text-zinc-600">{t.site.organisation.name}{t.site.organisation.contactPhone?` · ${t.site.organisation.contactPhone}`:""}</p>{t.site.organisation.registrationNo&&<p className="text-xs text-zinc-600">Reg. No: {t.site.organisation.registrationNo}</p>}</div><img src={qr} alt="Verification QR code" className="h-24 w-24"/></div><div className="mt-4 flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-[0.15em]">Weighbridge Ticket</h2>{order?.type&&<span className="rounded border border-zinc-900 px-2 py-0.5 text-xs font-bold uppercase tracking-wider">{order.type}</span>}</div><p className="mt-1 font-mono text-3xl font-bold">{t.waybillNumber}</p><dl className="mt-4 divide-y divide-zinc-200 border-t border-zinc-200 text-sm">
  <Field label="Reg No" value={t.vehicle.plate}/>
  <Field label="Trailer" value={trailerReg??"—"}/>
  <Field label="Operator" value={t.operator?`${t.operator.firstName} ${t.operator.lastName}`:"AUTOMATED"}/>
  <Field label="Transport Company" value={t.booking.transporterOrganisation.name}/>
  <Field label="Date & Time In" value={t.entryAt?t.entryAt.toLocaleString("en-ZA",{timeZone:tz}):"—"}/>
  <Field label="Date & Time Out" value={t.exitAt?t.exitAt.toLocaleString("en-ZA",{timeZone:tz}):"—"}/>
  <Field label="Supplier / Origin" value={supplierOrigin}/>
  <Field label="Destination" value={destination}/>
  <Field label="Product" value={order?.product??t.commodity}/>
  <Field label="Order No." value={order?.orderNumber??"—"}/>
  <Field label="External Ref" value={t.booking.reference}/>
  <Field label="Stockpile Ref" value={order?.stockpile??"—"}/>
  <Field label="Comment" value={order?.notes??"—"}/>
</dl><div className="grid grid-cols-3 gap-4 border-y-2 border-zinc-900 py-6 text-center my-4"><Weight label="Tare" value={formatKg(t.tareWeightKg)}/><Weight label="Gross" value={formatKg(t.grossWeightKg)}/><Weight label="Nett" value={formatKg(t.netWeightKg)} strong/></div><Field label="Load status" value={t.overload?`FAIL · ${formatKg(t.overloadVarianceKg)} variance`:"PASS"}/><div className="mt-8 flex justify-between gap-8"><div className="w-1/2"><p className="text-xs uppercase text-zinc-500">Driver</p><p className="mt-1 font-bold">{t.driver.firstName} {t.driver.lastName}</p><p className="text-xs text-zinc-600">Licence {t.driver.licenceNumber}</p><p className="mt-6 border-t border-zinc-900 pt-1 text-xs text-zinc-500">Sign</p></div><div className="w-1/2"><p className="text-xs uppercase text-zinc-500">Operator</p><p className="mt-1 font-bold">{t.operator?`${t.operator.firstName} ${t.operator.lastName}`:"AUTOMATED"}</p><p className="mt-6 border-t border-zinc-900 pt-1 text-xs text-zinc-500">Sign</p></div></div><p className="mt-8 border-t border-zinc-300 pt-4 text-[10px] text-zinc-500">This ticket is protected by a SHA-256 hash chain. Verify using the QR code or cloud verification URL.</p><p className="break-all font-mono text-[9px] text-zinc-400">{t.integrityHash}</p></div><div className="mx-auto mt-4 max-w-3xl print:hidden"><p className="mb-2 text-xs text-zinc-500">{t.printCount>0?`Printed ${t.printCount} time${t.printCount===1?"":"s"} already — further downloads are recorded as reprints.`:"Not yet printed."}</p><div className="flex flex-wrap gap-2"><Button asChild><Link href={`/api/transactions/${t.id}/waybill?copy=CLIENT${reprintFlag}`}>Client / office copy</Link></Button><Button asChild><Link href={`/api/transactions/${t.id}/waybill?copy=DRIVER${reprintFlag}`}>Driver / transporter copy</Link></Button><Button asChild><Link href={`/api/transactions/${t.id}/waybill?copy=SECURITY${reprintFlag}`}>Security / gate copy</Link></Button><Button variant="secondary" asChild><Link href={`/api/transactions/${t.id}/waybill?format=thermal${reprintFlag}`}>Thermal format</Link></Button></div></div></main>}
function Field({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 py-1.5"><dt className="text-xs uppercase tracking-wide text-zinc-500">{label}</dt><dd className="text-right font-semibold">{value}</dd></div>}
function Weight({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div><p className="text-xs uppercase text-zinc-500">{label}</p><p className={`${strong?"text-3xl":"text-2xl"} mt-1 font-mono font-bold`}>{value}</p></div>}
