import { UserRole } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { fail,ok,requireRole } from "@/lib/api";
import { normalisePlate } from "@/lib/utils";
import { vehicleSchema } from "@/lib/validation";
async function allowed(id:string,session:{user:{role:UserRole;organisationId:string|null}}){const vehicle=await prisma.vehicle.findUnique({where:{id},include:{organisation:true,trailers:true}});if(!vehicle)return null;if(session.user.role==="TRANSPORTER"&&vehicle.organisationId!==session.user.organisationId)return null;return vehicle}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const a=await requireRole([UserRole.TRANSPORTER,UserRole.OPERATOR,UserRole.ADMIN,UserRole.SECURITY]);if(a.error)return a.error;const {id}=await params;const vehicle=await allowed(id,a.session!);return vehicle?ok(vehicle):fail("Vehicle not found",404)}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){const a=await requireRole([UserRole.ADMIN]);if(a.error)return a.error;const {id}=await params;if(!await allowed(id,a.session!))return fail("Vehicle not found",404);const parsed=vehicleSchema.partial().safeParse(await request.json().catch(()=>null));if(!parsed.success)return fail("Invalid vehicle update",422);const {organisationId: _ignoredOrganisationId, ...safeUpdate}=parsed.data;const data={...safeUpdate,...(parsed.data.plate?{plate:parsed.data.plate.toUpperCase(),plateNormalized:normalisePlate(parsed.data.plate)}:{})};return ok(await prisma.vehicle.update({where:{id},data}))}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const a=await requireRole([UserRole.ADMIN]);if(a.error)return a.error;const {id}=await params;if(!await allowed(id,a.session!))return fail("Vehicle not found",404);const vehicle=await prisma.vehicle.update({where:{id},data:{status:"SUSPENDED",deletedAt:new Date()}});return ok(vehicle)}
