import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { mineScope } from "@/lib/access";
import { AppShell } from "@/components/app-shell";
import { isPlatformSuperAdmin } from "@/lib/permissions";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
export default async function Fraud(){const s=await auth();if(!s?.user)redirect("/login");const callerOrg=s.user.organisationId;const scope=mineScope(callerOrg);const [incidents,vehicles]=await Promise.all([prisma.incident.findMany({where:{type:{in:["FRAUD_ALERT","CLONE_DETECTION","ROUTE_DEVIATION","TARE_DRIFT"]},site:scope},include:{vehicle:true,site:true},orderBy:{createdAt:"desc"},take:100}),prisma.vehicle.findMany({where:callerOrg?{bookings:{some:{site:{organisationId:callerOrg}}}}:{},orderBy:{anomalyScore:"desc"},take:10})]);return <AppShell role={s.user.role} userName={s.user.name??"Admin"} orgName={s.user.organisationName} isSuperAdmin={isPlatformSuperAdmin(s.user)}><div className="space-y-4"><div><h1 className="text-2xl font-semibold text-foreground">Fraud intelligence</h1><p className="text-xs text-muted-foreground">Cross-site variance, clone detection, tare drift and route anomalies.</p></div><Card><CardHeader><CardTitle>Highest-risk vehicles</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{vehicles.map(x=><div key={x.id} className="rounded-sm border border-border p-3"><p className="font-mono text-sm">{x.plate}</p><p className="mt-2 text-2xl font-semibold">{Number(x.anomalyScore).toFixed(0)}</p><p className="text-2xs uppercase tracking-wider text-muted-foreground">Anomaly score</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Detected patterns</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Vehicle</TableHead><TableHead>Site</TableHead><TableHead>Detection</TableHead><TableHead>Severity</TableHead><TableHead>Score</TableHead></TableRow></TableHeader><TableBody>{incidents.map(x=><TableRow key={x.id}><TableCell>{x.createdAt.toLocaleString("en-ZA")}</TableCell><TableCell>{x.vehicle?.plate??"—"}</TableCell><TableCell>{x.site.code}</TableCell><TableCell><p className="font-medium">{x.title}</p><p className="max-w-xl text-xs text-muted-foreground">{x.description}</p></TableCell><TableCell><Badge variant={x.severity==="CRITICAL"||x.severity==="HIGH"?"destructive":"warning"}>{x.severity}</Badge></TableCell><TableCell>{Number(x.anomalyScore).toFixed(0)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div></AppShell>}
