import { UserRole } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { fail,ok,requireRole } from "@/lib/api";
import { audit } from "@/lib/audit";
import { siteIdentifierWhere } from "@/lib/utils";
const schema=z.object({operatingStart:z.string().regex(/^\d{2}:\d{2}$/).optional(),operatingEnd:z.string().regex(/^\d{2}:\d{2}$/).optional(),maxCapacityKg:z.number().int().min(1000).max(200000).optional(),stabilityThresholdKg:z.number().int().min(1).max(1000).optional(),stabilityDurationSeconds:z.number().int().min(1).max(30).optional(),overloadTolerancePercent:z.number().min(0).max(25).optional(),emptyVehicleMaxKg:z.number().int().min(1000).max(50000).optional(),loadedVehicleMaxKg:z.number().int().min(10000).max(150000).optional(),positioningHoldSeconds:z.number().int().min(1).max(20).optional(),turnaroundThresholdMinutes:z.number().int().min(5).max(1440).optional(),journeyWindowGraceMinutes:z.number().int().min(0).max(1440).optional(),autoApprovalEnabled:z.boolean().optional(),requireInsuranceValid:z.boolean().optional(),requireDriverLicenceValid:z.boolean().optional(),retentionYears:z.number().int().min(1).max(10).optional()});
async function site(id:string){return prisma.site.findFirst({where:siteIdentifierWhere(id),include:{config:true}})}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const a=await requireRole([UserRole.OPERATOR,UserRole.ADMIN,UserRole.SECURITY]);if(a.error)return a.error;const {id}=await params;const row=await site(id);if(!row)return fail("Site not found",404);const callerOrg=a.session!.user.organisationId;if(callerOrg&&row.organisationId!==callerOrg)return fail("Site not found",404);return ok(row.config)}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){const a=await requireRole([UserRole.ADMIN]);if(a.error)return a.error;const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return fail(parsed.error.issues[0]?.message??"Invalid site configuration",422);const {id}=await params;const row=await site(id);if(!row)return fail("Site not found",404);const callerOrg=a.session!.user.organisationId;if(callerOrg&&row.organisationId!==callerOrg)return fail("Site not found",404);const config=await prisma.siteConfig.upsert({where:{siteId:row.id},create:{siteId:row.id,...parsed.data},update:parsed.data});await audit({userId:a.session!.user.id,action:"SITE_CONFIG_UPDATED",entityType:"site_config",entityId:config.id,beforeData:row.config,afterData:config});return ok(config)}
