/** Permission catalogue and built-in platform-level role definitions for the custom RBAC engine (Role/Permission/RolePermission). Shared by the seed script and any future admin tooling that needs the canonical list. */

export const PERMISSION_CATALOGUE: Array<{ key: string; description: string; category: string }> = [
  { key: "client.view", description: "View client organisation", category: "Client" },
  { key: "client.update", description: "Update client organisation", category: "Client" },
  { key: "site.view", description: "View sites", category: "Site" },
  { key: "site.create", description: "Create sites", category: "Site" },
  { key: "site.update", description: "Update sites", category: "Site" },
  { key: "user.view", description: "View users", category: "User" },
  { key: "user.invite", description: "Invite users", category: "User" },
  { key: "user.update", description: "Update users", category: "User" },
  { key: "user.disable", description: "Disable users", category: "User" },
  { key: "role.view", description: "View roles", category: "Role" },
  { key: "role.create", description: "Create roles", category: "Role" },
  { key: "role.update", description: "Update roles", category: "Role" },
  { key: "role.assign", description: "Assign roles", category: "Role" },
  { key: "vehicle.view", description: "View vehicles", category: "Fleet" },
  { key: "vehicle.create", description: "Create vehicles", category: "Fleet" },
  { key: "vehicle.update", description: "Update vehicles", category: "Fleet" },
  { key: "driver.view", description: "View drivers", category: "Fleet" },
  { key: "driver.create", description: "Create drivers", category: "Fleet" },
  { key: "driver.update", description: "Update drivers", category: "Fleet" },
  { key: "transporter.view", description: "View transporters", category: "Transporter" },
  { key: "transporter.create", description: "Create transporters", category: "Transporter" },
  { key: "transporter.update", description: "Update transporters", category: "Transporter" },
  { key: "booking.view", description: "View bookings", category: "Booking" },
  { key: "booking.create", description: "Create bookings", category: "Booking" },
  { key: "booking.approve", description: "Approve bookings", category: "Booking" },
  { key: "booking.reject", description: "Reject bookings", category: "Booking" },
  { key: "transaction.view", description: "View transactions", category: "Transaction" },
  { key: "transaction.process", description: "Process transactions", category: "Transaction" },
  { key: "transaction.override", description: "Override transactions", category: "Transaction" },
  { key: "transaction.print", description: "Print transaction slips", category: "Transaction" },
  { key: "transaction.reprint", description: "Reprint transaction slips", category: "Transaction" },
  { key: "incident.view", description: "View incidents", category: "Incident" },
  { key: "incident.create", description: "Create incidents", category: "Incident" },
  { key: "incident.resolve", description: "Resolve incidents", category: "Incident" },
  { key: "hardware.view", description: "View hardware status", category: "Hardware" },
  { key: "hardware.control", description: "Control hardware", category: "Hardware" },
  { key: "report.view", description: "View reports", category: "Report" },
  { key: "report.export", description: "Export reports", category: "Report" },
  { key: "order.view", description: "View service orders", category: "Service Order" },
  { key: "order.create", description: "Create service orders", category: "Service Order" },
  { key: "order.update", description: "Update service orders", category: "Service Order" },
  { key: "order.assign", description: "Assign service orders", category: "Service Order" },
  { key: "configuration.view", description: "View site configuration", category: "Configuration" },
  { key: "configuration.update", description: "Update site configuration", category: "Configuration" },
  { key: "source.view", description: "View sources", category: "Master Data" },
  { key: "source.create", description: "Create sources", category: "Master Data" },
  { key: "source.update", description: "Update sources", category: "Master Data" },
  { key: "source.disable", description: "Disable sources", category: "Master Data" },
  { key: "destination.view", description: "View destinations", category: "Master Data" },
  { key: "destination.create", description: "Create destinations", category: "Master Data" },
  { key: "destination.update", description: "Update destinations", category: "Master Data" },
  { key: "destination.disable", description: "Disable destinations", category: "Master Data" },
  { key: "product.view", description: "View products", category: "Master Data" },
  { key: "product.create", description: "Create products", category: "Master Data" },
  { key: "product.update", description: "Update products", category: "Master Data" },
  { key: "product.disable", description: "Disable products", category: "Master Data" },
  { key: "weighbridge_order.view", description: "View operational orders", category: "Order" },
  { key: "weighbridge_order.create", description: "Create operational orders", category: "Order" },
  { key: "weighbridge_order.update", description: "Update operational orders", category: "Order" },
];

/** null = every permission in the catalogue (mirrors current ADMIN behaviour within an org). */
export const BUILT_IN_ROLE_PERMISSIONS: Record<string, string[] | null> = {
  CLIENT_ADMIN: null,
  SUPERVISOR: [
    "client.view", "site.view", "user.view", "role.view", "vehicle.view", "driver.view", "transporter.view",
    "booking.view", "booking.approve", "booking.reject", "transaction.view", "transaction.override", "transaction.print", "transaction.reprint",
    "incident.view", "incident.resolve", "hardware.view", "hardware.control", "report.view", "report.export",
    "order.view", "order.create", "order.update", "order.assign", "configuration.view",
    "source.view", "source.create", "source.update", "destination.view", "destination.create", "destination.update",
    "product.view", "product.create", "product.update", "weighbridge_order.view", "weighbridge_order.create", "weighbridge_order.update"
  ],
  OPERATOR: [
    "site.view", "vehicle.view", "driver.view", "booking.view", "booking.create",
    "transaction.view", "transaction.process", "transaction.print", "transaction.reprint", "incident.view", "incident.create",
    "hardware.view", "hardware.control", "report.view", "order.view", "order.create",
    "source.view", "destination.view", "product.view", "weighbridge_order.view"
  ],
  VIEWER: [
    "client.view", "site.view", "user.view", "vehicle.view", "driver.view", "transporter.view",
    "booking.view", "transaction.view", "incident.view", "hardware.view", "report.view", "order.view", "configuration.view",
    "source.view", "destination.view", "product.view", "weighbridge_order.view"
  ],
};
