import { redirect } from "next/navigation";
import { subDays } from "date-fns";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { AppShell } from "@/components/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatKg } from "@/lib/utils";
import { mineScope } from "@/lib/access";

export default async function AdminPage(){const s=await auth();if(!s?.user)redirect("/login");const since=subDays(new Date(),7);const scope=mineScope(s.user.organisationId);const [sites,tx,openIncidents,hardware]=await Promise.all([prisma.site.findMany({where:{isActive:true,...scope},include:{_count:{select:{transactions:true,incidents:true}}}}),prisma.weighbridgeTransaction.aggregate({where:{capturedAt:{gte:since},site:scope},_count:true,_sum:{netWeightKg:true},_avg:{turnaroundSeconds:true}}),prisma.incident.count({where:{status:{in:["OPEN","ACKNOWLEDGED"]},site:scope}}),prisma.hardwareStatus.findMany({where:{site:scope},orderBy:{lastSeen:"desc"},distinct:["siteId"],include:{site:true}})]);return <AppShell role={s.user.role} userName={s.user.name??"Administrator"} orgName={s.user.organisationName}><div className="space-y-4"><div><h1 className="text-2xl font-semibold text-foreground">Enterprise overview</h1><p className="text-xs text-muted-foreground">Cross-site performance, risk and hardware availability.</p></div><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[{l:"Active sites",v:sites.length},{l:"7-day trucks",v:tx._count},{l:"7-day tonnage",v:`${((tx._sum.netWeightKg??0)/1000).toFixed(1)} t`},{l:"Open incidents",v:openIncidents}].map(x=><Card key={x.l}><CardContent className="p-4"><p className="text-2xs uppercase tracking-wider text-muted-foreground">{x.l}</p><p className="mt-1 font-mono text-2xl font-semibold">{x.v}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Site performance</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Site</TableHead><TableHead>Location</TableHead><TableHead>Transactions</TableHead><TableHead>Incidents</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{sites.map(site=><TableRow key={site.id}><TableCell><p className="font-medium">{site.name}</p><p className="font-mono text-xs text-muted-foreground">{site.code}</p></TableCell><TableCell>{site.address}</TableCell><TableCell>{site._count.transactions}</TableCell><TableCell>{site._count.incidents}</TableCell><TableCell><Badge>Operational</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Hardware health</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{hardware.map(item=><div key={item.id} className="rounded-sm border border-border p-3"><div className="flex items-center justify-between"><p className="text-sm font-medium">{item.site.name}</p><Badge variant={item.health==="ONLINE"?"default":item.health==="DEGRADED"?"warning":"destructive"}>{item.health}</Badge></div><p className="mt-2 text-xs text-muted-foreground">Last seen {item.lastSeen.toLocaleString("en-ZA")}</p></div>)}</CardContent></Card></div></AppShell>}
